purescript-contrib/purescript-css

- bower.json
- src/Css/Font.purs
- src/Css/FontFace.purs
- src/Css/Property.purs
- src/Css/Render.purs
- src/Css/Stylesheet.purs
Not ready to merge yet. Waiting on paf31/purescript-nonempty#1 (or some other equivalent solution to be merged).
> Switch to purescript-nonempty

- site/Main.js
- site/Main.purs
Hey there,
I was experimenting with this library and had to revise a few minor things to get the Site module to build with the latest version of the purescript compiler.  Specifically I had to change the original import of Data.Array.NonEmpty to Data.NonEmpty, I had to break out the foreign imports into their own js module, and I had to add a bunch of .0's to change many of the ints to numbers.  I'm not sure if this is useful to you or not, but since it is done I thought I would share it in case that it is.
Thank you for the excellent library.  I am not a professional developer so please excuse me if I am not handling this correctly as this is literally the first pull request I have ever initiated.
> Fixed NEL import; Fixed Number/Int issues; Builds Now

- src/CSS.purs
- test/Main.purs
This pull-request adds a top-level `CSS` module that exports all the the `CSS.*` sub-modules, except for `CSS.Render`.  It also removes an uneeded import from the testing file.
One small problem is that `maxWidth` is exported from both `CSS.Geometry` and `CSS.Media`.  I hid the `maxWidth` from `CSS.Media`.  I made this decision pretty much arbitrarily, so if you think something else should be done, let me know.
Also, please let me know if there are modules other than `CSS.Render` that shouldn't be exported.
> Add top-level CSS module

- src/CSS/Overflow.purs
- src/CSS/TextAlign.purs
Added `text-align` and `overflow` 
@garyb, please review
> text-align, overflow

- src/CSS/Animation.purs
- src/CSS/Render.purs
@beckyconning could you please take a look? 
This makes `animation` and `keyframes` funcs rendering unprefixed and prefixed version. This doesn't change API and I suggest this should a patch version.
> added prefixed animation and keyframes

- src/CSS/Render.purs
- test/Main.purs
I've fixed two issues:
* generated stylesheet for nested nodes was incorrect - there was newline character missing after parent properties block),
* I've added added small improvement regarding nested nodes rendering - empty rules blocks are skipped from output
I've added two test case for every change.
> Nested node rendering fixes

- src/CSS.purs
- src/CSS/Text/Whitespace.purs
Hi everyone,
I ran into a property I needed: white-space and it's attributes: normal, nowrap, pre, pre-wrap, pre-line.
I figured I would create a sub directory, since this is the white-space property of the Text portion of the css spec: https://www.w3.org/TR/css-text-3/
Not sure if that's acceptable to you guys. I will probably run across more properties/attributes that I need and i'll try to PR them in, just need to know the correct way to go about it.
Thanks!
FWIW, I successfully tested this on an app i'm writing.
> Implements the white-space property

- src/CSS/FontFace.purs
- test/Main.purs
Issue "FontFaceFormat is not put in quotes #56" fixed
> FontFaceFormat put in quotes

- bower.json
Changes in new version are not that braking only internal representation has changed for Color and ColorScale which do not affect ps-css. so we can safely use wider range of ps-colors.
This is the change tigerring new version https://github.com/sharkdp/purescript-colors/pull/31
> update ps-colors version range

- .gitignore
- src/CSS/Animation.purs
- src/CSS/Background.purs
- src/CSS/Border.purs
- src/CSS/Box.purs
- src/CSS/Display.purs
- src/CSS/Flexbox.purs
- src/CSS/Font.purs
- src/CSS/FontFace.purs
- src/CSS/Gradient.purs
- src/CSS/ListStyle/Image.purs
- src/CSS/ListStyle/Position.purs
- src/CSS/ListStyle/Type.purs
- src/CSS/Overflow.purs
- src/CSS/Property.purs
- src/CSS/Render.purs
- src/CSS/Selector.purs
- src/CSS/Size.purs
- src/CSS/Stylesheet.purs
- src/CSS/Text.purs
- src/CSS/Text/Transform.purs
- src/CSS/Text/Whitespace.purs
- src/CSS/TextAlign.purs
- src/CSS/Time.purs
- src/CSS/Transform.purs
- src/CSS/Transition.purs
Should fix #73.
I had to manually implement `Show` type class in several cases
> Remove purescript-generics, upgrade dependencies

- src/CSS/Selector.purs
- test/Main.purs
Fixes typo [here](https://github.com/slamdata/purescript-css/blob/7a39810efe99921d15ce1fceb0bc2be165e34f01/src/CSS/Selector.purs#L85).
Also:
* Increased the precedence of these selector operators (to make it possible to omit parentheses), but maybe its better to lower the precedence of `?` operator. Not sure if this might be a breaking change though
* Added a couple of tests
resolves #75
> Fix selector operators

- src/CSS/Size.purs
Ported [from Clay](https://github.com/sebastiaanvisser/clay/blob/03f90289eba89fa72cfc81b1f9685f699c954fd9/src/Clay/Size.hs#L123).
Resolves #79
> Add unitless size

- src/CSS.purs
- src/CSS/Text/Overflow.purs
- src/CSS/Text/Transform.purs
- test/Main.purs
This PR adds only basic support for `text-overflow` (I believe only `fade` is missing), but should cover most use-cases of this property.
Resolves #96
> Add text-overflow CSS property

- src/CSS.purs
- src/CSS/Render.purs
- src/CSS/Selector.purs
- test/Main.purs
This PR is a 100% port from Clay, no other additions from my side.
Resolves #98
> Add more selector combinators

- src/CSS/Property.purs
- src/CSS/Size.purs
This allows terms of type `Key a` to be coerced to type `Key b` when `Coercible a b` holds but prevents terms of type `Size a` and `Angle a` to be coerced to type `Size b` and `Angle b`. The reasoning being that keys of some type can be associated to to terms of types with the same representation but not arbitrary types and values with absolute or relative sizes and angles in degrees or radians don’t describe the same runtime values.
> Add roles declarations to forbid unsafe coercions

- bower.json
- spago.dhall
Generic instances were removed in https://github.com/purescript-contrib/purescript-css/pull/76 but generics-rep was still listed in the bower.json and the spago.dhall files, this seems to be an oversight.
> Remove the dependency on generics-rep

- CHANGELOG.md
- src/CSS/Flexbox.purs
- test/Main.purs
The `flex` shorthand, `flex-grow`, and `flex-shrink` properties appear to allow Numbers as values, not just Ints.  I ran into this tonight while trying to implement a flex-based slider control.
See below:
https://drafts.csswg.org/css-flexbox-1/#flex-property
> flex-grow and flex-shrink typed as `Number`

- .github/workflows/ci.yml
Update Github Actions from Purescript 0.14.0-rc5 to 0.14.0
---
**Checklist:**
> update CI Purescript version

- CHANGELOG.md
- spago.dhall
- src/CSS/Property.purs
- src/CSS/Render.purs
Self-explanatory
---
**Checklist:**
> Fix warnings revealed by v0.14.1 PS release

- CHANGELOG.md
- src/CSS/Animation.purs
- src/CSS/Border.purs
- src/CSS/Geometry.purs
- src/CSS/ListStyle.purs
- src/CSS/Property.purs
- src/CSS/Text/Shadow.purs
- src/CSS/Transform.purs
- test/Main.purs
Finishes #44 and resolves the merge conflict
---
**Checklist:**
> Finish PR 44 - Remove Nested Tuple usage

- .github/workflows/ci.yml
- .gitignore
- .tidyrc.json
- CHANGELOG.md
- packages.dhall
- src/CSS/Background.purs
- src/CSS/Box.purs
- src/CSS/Common.purs
- src/CSS/Cursor.purs
- src/CSS/Flexbox.purs
- src/CSS/Gradient.purs
- src/CSS/Render.purs
- src/CSS/Selector.purs
- src/CSS/Size.purs
- src/CSS/Stylesheet.purs
- src/CSS/Text/Shadow.purs
- src/CSS/Text/Transform.purs
- src/CSS/TextAlign.purs
- src/CSS/Time.purs
- src/CSS/Transform.purs
- src/CSS/Transition.purs
- test/Main.purs
Introduces the [`purs-tidy`](https://github.com/natefaubion/purescript-tidy) formatter. This formatter is a lightly opinionated tool we use to maintain a consistent style in the contrib libraries.
We ordinarily restrict to tools provided by the `core` or `contrib` projects. This tool is not, but it was developed and is maintained by core team members, and because it's a formatter it can't block maintenance or release of this library even in the event something goes catastrophically wrong with it.
---
**Checklist:**
> Introduce purs-tidy formatter

- CHANGELOG.md
- spago.dhall
- src/CSS.purs
- src/CSS/Border.purs
- src/CSS/Gradient.purs
- src/CSS/Media.purs
- src/CSS/Size.purs
- test/Main.purs
This change adds support for [`calc` expressions](https://developer.mozilla.org/en-US/docs/Web/CSS/calc()) (see #55). This is pretty much a direct port from [Clay](https://github.com/sebastiaanvisser/clay), which appears to be the original basis for this library. In the process of implementing this feature, I've also aligned the size data types with Clay, which is obviously a significant breaking change but hopefully a worthwhile one...
For reference, here are the relevant modules in Clay for comparison:
1. [src/Size.hs](https://github.com/sebastiaanvisser/clay/blob/master/src/Clay/Size.hs)
2. [src/Border.hs](https://github.com/sebastiaanvisser/clay/blob/master/src/Clay/Border.hs)
3. [src/Gradient.hs](https://github.com/sebastiaanvisser/clay/blob/master/src/Cl …
> Support for calc expressions. Addresses #55.

- CHANGELOG.md
- src/CSS/Display.purs
- test/CSS/DisplaySpec.purs
- test/Main.purs
This pull request adds support for the [`visibility` property](https://developer.mozilla.org/en-US/docs/Web/CSS/visibility). Mostly a direct port from [Clay](https://github.com/sebastiaanvisser/clay/blob/master/src/Clay/Display.hs#L188-L197) with the following caveats in mind:
* `separate` is not a valid value: https://github.com/sebastiaanvisser/clay/issues/225
* `auto` is not a valid value: https://github.com/sebastiaanvisser/clay/issues/224
* `unset` _is_ a valid value: https://github.com/sebastiaanvisser/clay/issues/224
---
**Checklist:**
> Add support for visibility property. Resolves #146.
